#!/bin/bash
# ex: set shiftwidth=4 tabstop=4 expandtab:

set -o errexit

##### PPA #####
. setup-scripts/setup-ppa

##### PS1 #####
. setup-scripts/setup-ps1

##### SSH #####
. setup-scripts/setup-ssh

##### VIM #####
. setup-scripts/setup-vim

##### NODE #####
. setup-scripts/setup-node

##### GIT #####
. setup-scripts/setup-git
