#!/bin/bash
# ex: set shiftwidth=4 tabstop=4 expandtab:

printf '#######################################\n'
printf 'Setting up Node \n'
printf '#######################################\n'

if [[ -r "$HOME/.nvm" ]]
then
    printf 'nvm already detected. \n Node versions installed:\n'
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
    nvm ls
else
    printf 'Installing nvm'
    curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash

    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

    nvm install node
    printf 'Node version installed'
    nvm ls
fi
